title: Xiaxin Shen # your name (or website title) here
logo: "/images/logo_real.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://ece.princeton.edu/"> PhD Student in ECE</a> at <a href="https://www.princeton.edu/">Princeton University</a> 
  <br><br>
  # My research interests lie in systems, machine learning, and privacy <br><br>
  Email: xiaxin.shen AT princeton DOT edu
  <br><br>
  <a href="pdf/XiaxinShen_CV.pdf">View My CV</a>  
  <br><br>
  <a href="https://www.linkedin.com/in/xiaxin-s-831153194/">View My LinkedIn Profile</a>



theme: jekyll-theme-minimal

google_analytics: UA-211723924-1 # your Google Analytics tracking ID here