title: Xiaxin Shen # your name (or website title) here
logo: "/images/logo_real.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://polytechnic.purdue.edu/degrees/computer-and-information-technology">Computer and Information Technology </a> Student at <a href="https://www.purdue.edu/">Purdue University</a> 
  <br><br>
  Her research interests include machine learning, deep learning, computer vision, malware detection, reinforcement learning, robotics and security.
  <br><br>
  <a href="pdf/Resume.pdf">View My Resume</a><a href="pdf/CV.pdf">/CV</a>
  <br><br>
  <a href="https://www.linkedin.com/in/xiaxin-s-831153194/">View My LinkedIn Profile</a> 



  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
