title: Xiaxin Shen # your name (or website title) here
logo: "/images/logo_real.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://polytechnic.purdue.edu/degrees/computer-and-information-technology">Majoring in Computer and Information Technology </a> at <a href="https://www.purdue.edu/">Purdue University</a> 
  <br><br>
  Her research interests include robotics, computer vision, deep learning, machine learning, reinforcement learning, and security.
  <br><br>
  Email: shen452 AT purdue DOT edu
  <br><br>
  <a href="pdf/CV.pdf">View My CV (short)</a> / <a href="pdf/XiaxinShen_CV_long.pdf">CV (long)</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/xiaxin-s-831153194/">View My LinkedIn Profile</a>



theme: jekyll-theme-minimal

google_analytics: UA-211723924-1 # your Google Analytics tracking ID here